<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ValueValidators\\' => array($vendorDir . '/data-values/validators/src'),
    'Symfony\\Component\\Filesystem\\' => array($vendorDir . '/symfony/filesystem'),
    'Symfony\\Component\\DependencyInjection\\' => array($vendorDir . '/symfony/dependency-injection'),
    'Symfony\\Component\\Config\\' => array($vendorDir . '/symfony/config'),
    'Serializers\\' => array($vendorDir . '/serialization/serialization/src/Serializers'),
    'SMW\\' => array($baseDir . '/src'),
    'ParserHooks\\' => array($vendorDir . '/mediawiki/parser-hooks/src'),
    'ParamProcessor\\' => array($vendorDir . '/param-processor/param-processor/src', $baseDir . '/extensions/Validator/src/ParamProcessor'),
    'Onoi\\MessageReporter\\' => array($vendorDir . '/onoi/message-reporter/src'),
    'Onoi\\HttpRequest\\' => array($vendorDir . '/onoi/http-request/src'),
    'Onoi\\EventDispatcher\\' => array($vendorDir . '/onoi/event-dispatcher/src'),
    'Onoi\\CallbackContainer\\' => array($vendorDir . '/onoi/callback-container/src'),
    'Onoi\\Cache\\' => array($vendorDir . '/onoi/cache/src'),
    'Onoi\\BlobStore\\' => array($vendorDir . '/onoi/blob-store/src'),
    'Deserializers\\' => array($vendorDir . '/serialization/serialization/src/Deserializers'),
);
